[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/blm"
  to = "/blm.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200